version: "3"

services:
    flask-app:
        container_name: pysite
        build: ./
        ports:
            - "8000:5000"
        volumes:
            - ./app:/app
        networks:
            - backend

    mysql-db:
        container_name: app_db
        image: mysql:8.0.32
        environment:
            MYSQL_ROOT_PASSWORD: rootsql
            MYSQL_DATABASE: app_db
        ports:
            - '3308:3306'
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database: