"""director

Revision ID: 22a5b35ab7f5
Revises: e141753fa7a8
Create Date: 2023-02-14 11:58:24.523954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a5b35ab7f5'
down_revision = 'e141753fa7a8'
branch_labels = None
depends_on = None

convention = {
  "ix": "ix_%(column_0_label)s",
  "uq": "uq_%(table_name)s_%(column_0_name)s",
  "ck": "ck_%(table_name)s_%(constraint_name)s",
  "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
  "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_director', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_film_id_director', 'director', ['id_director'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_director')

    # ### end Alembic commands ###
