"""mysql and poster

Revision ID: 62d72511945e
Revises: 
Create Date: 2023-03-20 14:33:06.536772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d72511945e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['poster'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
