"""film_1

Revision ID: e141753fa7a8
Revises: 
Create Date: 2023-02-14 11:49:29.953496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e141753fa7a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_genre',
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('id_genre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_film'], ['film.id'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('about_me', sa.String(length=250), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('id_film_watched', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_film_watched'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('film_genre')
    op.drop_table('genre')
    op.drop_table('film')
    op.drop_table('director')
    # ### end Alembic commands ###
